name: Trufflehog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
         scanArguments: "--regex --max_depth=5 --rules /regexes.json --json > trufflehog.json" # Add custom options here*

      - name: Upload trufflehog results to artefacts
        uses: actions/upload-artifact@v1
        with:
            name: Trufflehog
            path: trufflehog.json