name: Trufflehog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
            scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" --json # Add custom options here*
